name: License check
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Fix License Header
        uses: apache/skywalking-eyes/header@main
        with:
          config: .licenserc.yaml
          log: debug
          mode: fix
      - name: Apply Changes
        uses: EndBug/add-and-commit@v4
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: License Bot
          author_email: license_bot@github.com
          message: 'Automatic application of license header'